#!/bin/zsh
rm -rf dist/CC\ 2014 \
rm -rf dist/CC\ 2015 \
&& mkdir dist/CC\ 2014 \
&& mkdir dist/CC\ 2015 \
&& mkdir dist/CC\ 2014/assets \
&& mkdir dist/CC\ 2015/assets \
&& cp html-panel/installer.jsx dist/CC\ 2014 \
&& cp html-panel/installer.jsx dist/CC\ 2015 \
&& cp -r scripts/photoshop/ dist/CC\ 2014/assets/scripts \
&& cp -r scripts/bridge/ dist/CC\ 2014/assets/bridge-context-menu \
&& cp -r scripts/photoshop/ dist/CC\ 2015/assets/scripts \
&& cp -r scripts/bridge/ dist/CC\ 2015/assets/bridge-context-menu \
&& cd html-panel \
&& gulp \
&& cd .. \
&& cp -r html-panel/dist/ dist/temp-2014 \
&& cp -r html-panel/dist/ dist/temp-2015 \
&& mv dist/temp-2014/CSXS/manifest-cc-2014.xml dist/temp-2014/CSXS/manifest.xml \
&& rm dist/temp-2014/CSXS/manifest-cc-2015.xml \
&& rm dist/temp-2014/.debug \
&& mv dist/temp-2014/js/CSInterface5.js dist/temp-2014/js/CSInterface.js \
&& rm dist/temp-2014/js/CSInterface6.js \
&& mv dist/temp-2015/CSXS/manifest-cc-2015.xml dist/temp-2015/CSXS/manifest.xml \
&& rm dist/temp-2015/CSXS/manifest-cc-2014.xml \
&& rm dist/temp-2015/.debug \
&& mv dist/temp-2015/js/CSInterface6.js dist/temp-2015/js/CSInterface.js \
&& rm dist/temp-2015/js/CSInterface5.js \
&& find . -name "*.DS_Store" -type f -delete; find . -name "*.ds_store" -type f -delete; \
zxpsigncmd -sign dist/temp-2014 dist/temp-2014.zxp lumens.p12 $1 -tsa https://timestamp.geotrust.com/tsa \
&& zxpsigncmd -sign dist/temp-2015 dist/temp-2015.zxp lumens.p12 $1 -tsa https://timestamp.geotrust.com/tsa \
&& rm -rf dist/temp-2014 \
&& rm -rf dist/temp-2015 \
&& unar dist/temp-2014.zxp -o dist \
&& unar dist/temp-2015.zxp -o dist \
&& rm dist/temp-2014.zxp \
&& rm dist/temp-2015.zxp \
&& mv dist/temp-2014/ dist/CC\ 2014/assets/html-panel \
&& mv dist/temp-2015/ dist/CC\ 2015/assets/html-panel
