#!/bin/zsh
rm -rf dist/CC\ 2014
rm -rf dist/CC\ 2015
rm -rf dist/CC\ 2015.5
rm -rf dist/CC\ 2018
rm -rf dist/CC\ 2019
rm -rf dist/2020

mkdir dist/CC\ 2014
mkdir dist/CC\ 2014/assets
cp html-panel/installer.jsx dist/CC\ 2014
cp html-panel/init.json dist/CC\ 2014
cp -r scripts/photoshop/ dist/CC\ 2014/assets/scripts
cp -r scripts/bridge/ dist/CC\ 2014/assets/bridge-context-menu

cp -r dist/CC\ 2014 dist/CC\ 2015
cp -r dist/CC\ 2014 dist/CC\ 2015.5
cp -r dist/CC\ 2014 dist/CC\ 2018
cp -r dist/CC\ 2014 dist/CC\ 2019
cp -r dist/CC\ 2014 dist/2020

cd html-panel
gulp
cd ..
cp -r html-panel/dist/ dist/temp-2014
cp -r html-panel/dist/ dist/temp-2015
cp -r html-panel/dist/ dist/temp-2015.5
cp -r html-panel/dist/ dist/temp-2018
cp -r html-panel/dist/ dist/temp-2019
cp html-panel/node_modules/adobe-cep/CEP_5.x/CSInterface.js dist/temp-2014/js/
cp html-panel/node_modules/adobe-cep/CEP_6.x/CSInterface.js dist/temp-2015/js/
cp html-panel/node_modules/adobe-cep/CEP_7.x/CSInterface.js dist/temp-2015.5/js/
cp html-panel/node_modules/adobe-cep/CEP_8.x/CSInterface.js dist/temp-2018/js/
cp html-panel/node_modules/adobe-cep/CEP_8.x/CSInterface.js dist/temp-2018/js/
cp html-panel/node_modules/adobe-cep/CEP_9.x/CSInterface.js dist/temp-2019/js/

rm dist/temp-2014/CSXS/*.xml
rm dist/temp-2015/CSXS/*.xml
rm dist/temp-2015.5/CSXS/*.xml
rm dist/temp-2018/CSXS/*.xml
rm dist/temp-2019/CSXS/*.xml
cp html-panel/src/CSXS/manifest-cc-2014.xml dist/temp-2014/CSXS/manifest.xml
cp html-panel/src/CSXS/manifest-cc-2015.xml dist/temp-2015/CSXS/manifest.xml
cp html-panel/src/CSXS/manifest-cc-2015.5.xml dist/temp-2015.5/CSXS/manifest.xml
cp html-panel/src/CSXS/manifest-cc-2018.xml dist/temp-2018/CSXS/manifest.xml
cp html-panel/src/CSXS/manifest-cc-2019.xml dist/temp-2019/CSXS/manifest.xml

rm dist/temp-2014/.debug
rm dist/temp-2015/.debug
rm dist/temp-2015.5/.debug
rm dist/temp-2018/.debug
rm dist/temp-2019/.debug
find . -name "*.DS_Store" -type f -delete; find . -name "*.ds_store" -type f -delete;

cp -r dist/temp-2019 dist/temp-2020

zxpsigncmd -sign dist/temp-2014 dist/temp-2014.zxp lumens.p12 $1 -tsa http://timestamp.digicert.com 
zxpsigncmd -sign dist/temp-2015 dist/temp-2015.zxp lumens.p12 $1 -tsa http://timestamp.digicert.com 
zxpsigncmd -sign dist/temp-2015.5 dist/temp-2015.5.zxp lumens.p12 $1 -tsa http://timestamp.digicert.com 
zxpsigncmd -sign dist/temp-2018 dist/temp-2018.zxp lumens.p12 $1 -tsa http://timestamp.digicert.com 
zxpsigncmd -sign dist/temp-2019 dist/temp-2019.zxp lumens.p12 $1 -tsa http://timestamp.digicert.com 
~/bin/zxp64/ZXPSignCmd-64bit -sign dist/temp-2020 dist/temp-2020.zxp lumens.p12 $1 -tsa http://timestamp.digicert.com 
rm -rf dist/temp-2014
rm -rf dist/temp-2015
rm -rf dist/temp-2015.5
rm -rf dist/temp-2018
rm -rf dist/temp-2019
rm -rf dist/temp-2020
unar dist/temp-2014.zxp -o dist
unar dist/temp-2015.zxp -o dist
unar dist/temp-2015.5.zxp -o dist
unar dist/temp-2018.zxp -o dist
unar dist/temp-2019.zxp -o dist
unar dist/temp-2020.zxp -o dist
rm dist/temp-2014.zxp
rm dist/temp-2015.zxp
rm dist/temp-2015.5.zxp
rm dist/temp-2018.zxp
rm dist/temp-2019.zxp
rm dist/temp-2020.zxp
mv dist/temp-2014/ dist/CC\ 2014/assets/html-panel
mv dist/temp-2015/ dist/CC\ 2015/assets/html-panel
mv dist/temp-2015.5/ dist/CC\ 2015.5/assets/html-panel
mv dist/temp-2018/ dist/CC\ 2018/assets/html-panel
mv dist/temp-2019/ dist/CC\ 2019/assets/html-panel
mv dist/temp-2020/ dist/2020/assets/html-panel
