#!/bin/zsh
rm -f ./hybrid/html5panel.zxp \
&& rm -rf ./hybrid/scripts \
&& cp -r ../scripts hybrid \
&&  zxpsigncmd -sign ./dist ./hybrid/html5panel.zxp lumens.p12 $1 -tsa https://timestamp.geotrust.com/tsa \
&& rm -f ../tychpanel_cc.zxp \
&& zxpsigncmd -sign hybrid ../tychpanel_cc.zxp lumens.p12 $1 -tsa https://timestamp.geotrust.com/tsa \
&& open ../tychpanel_cc.zxp
